// Guest storage: mirrors claude.js API but uses localStorage instead of the backend.
// All data lives in the browser and is cleared when the user signs in.

const DECKS_KEY = "studysprinter_guest_decks";
const DISMISSED_EXAMPLES_KEY = "studysprinter_dismissed_examples";
const EXAMPLE_STATS_KEY = "studysprinter_example_stats";
const EXAMPLE_FIRST_SEEN_KEY = "studysprinter_example_first_seen";
const PINNED_EXAMPLES_KEY = "studysprinter_pinned_examples";

function generateId() {
  return "guest-" + Math.random().toString(36).substr(2, 9) + "-" + Date.now();
}

function getDecks() {
  try {
    return JSON.parse(localStorage.getItem(DECKS_KEY) || "[]");
  } catch {
    return [];
  }
}

export function getExampleFirstSeen(id) {
  const firstSeen = JSON.parse(
    localStorage.getItem(EXAMPLE_FIRST_SEEN_KEY) || "{}",
  );
  if (!firstSeen[id]) {
    firstSeen[id] = new Date().toISOString();
    localStorage.setItem(EXAMPLE_FIRST_SEEN_KEY, JSON.stringify(firstSeen));
  }
  return firstSeen[id];
}

function saveDecks(decks) {
  localStorage.setItem(DECKS_KEY, JSON.stringify(decks));
}

export function dismissExampleDeck(id) {
  const dismissed = JSON.parse(
    localStorage.getItem(DISMISSED_EXAMPLES_KEY) || "[]",
  );
  if (!dismissed.includes(id)) {
    dismissed.push(id);
    localStorage.setItem(DISMISSED_EXAMPLES_KEY, JSON.stringify(dismissed));
  }
}

export function getDismissedExamples() {
  return JSON.parse(localStorage.getItem(DISMISSED_EXAMPLES_KEY) || "[]");
}

// Save a newly generated deck (content already generated by backend, just store it locally)
export function saveGuestDeck(deck) {
  const decks = getDecks();
  const newDeck = {
    ...deck,
    id: generateId(),
    pinned: false,
    created_at: new Date().toISOString(),
    last_studied: null,
    stats: {
      times_reviewed: 0,
      best_score: null,
      last_reviewed: null,
    },
  };
  decks.unshift(newDeck);
  saveDecks(decks);
  return newDeck;
}

// Get all decks for the sidebar (same shape as /study-sets response)
export function getGuestStudySets() {
  const decks = getDecks();
  return decks
    .sort((a, b) => {
      if (a.pinned !== b.pinned) return b.pinned - a.pinned;
      const aDate = a.last_studied || a.created_at;
      const bDate = b.last_studied || b.created_at;
      return new Date(bDate) - new Date(aDate);
    })
    .map((d) => ({
      id: d.id,
      title: d.title,
      summary: d.summary,
      created_at: d.created_at,
      pinned: d.pinned,
      last_studied: d.last_studied,
    }));
}

// Get a single full deck (same shape as /study-sets/{id} response)
export function getGuestStudySet(id) {
  const deck = getDecks().find((d) => d.id === id);
  if (!deck) throw new Error("Deck not found");
  return deck;
}

// Delete a deck
export function deleteGuestStudySet(id) {
  saveDecks(getDecks().filter((d) => d.id !== id));
  return { status: "deleted" };
}

// Toggle pin
export function toggleGuestPin(id) {
  const decks = getDecks();
  const deck = decks.find((d) => d.id === id);
  if (!deck) throw new Error("Deck not found");
  deck.pinned = !deck.pinned;
  saveDecks(decks);
  return { pinned: deck.pinned };
}

export function recordGuestStats(id, quizScore) {
  // Check if it's a regular guest deck
  const decks = getDecks();
  const deck = decks.find((d) => d.id === id);

  if (deck) {
    // Regular guest deck — save stats on the deck object
    const now = new Date().toISOString();
    deck.last_studied = now;
    deck.stats = deck.stats || {
      times_reviewed: 0,
      best_score: null,
      last_reviewed: null,
    };
    deck.stats.times_reviewed += 1;
    deck.stats.last_reviewed = now;
    if (
      quizScore !== null &&
      (deck.stats.best_score === null || quizScore > deck.stats.best_score)
    ) {
      deck.stats.best_score = quizScore;
    }
    saveDecks(decks);
  } else {
    // Example deck — save stats separately
    const allStats = JSON.parse(
      localStorage.getItem(EXAMPLE_STATS_KEY) || "{}",
    );
    const stats = allStats[id] || {
      times_reviewed: 0,
      best_score: null,
      last_reviewed: null,
    };
    const now = new Date().toISOString();
    stats.times_reviewed += 1;
    stats.last_reviewed = now;
    if (
      quizScore !== null &&
      (stats.best_score === null || quizScore > stats.best_score)
    ) {
      stats.best_score = quizScore;
    }
    allStats[id] = stats;
    localStorage.setItem(EXAMPLE_STATS_KEY, JSON.stringify(allStats));
  }
  return { status: "recorded" };
}

export function getGuestDeckStats(id) {
  // Check regular guest decks first
  const deck = getDecks().find((d) => d.id === id);
  if (deck) {
    const stats = deck.stats || {
      times_reviewed: 0,
      best_score: null,
      last_reviewed: null,
    };
    return {
      times_reviewed: stats.times_reviewed,
      best_score: stats.best_score,
      last_reviewed: stats.last_reviewed,
      total_cards_revealed: 0,
    };
  }

  // Check example deck stats
  const allStats = JSON.parse(localStorage.getItem(EXAMPLE_STATS_KEY) || "{}");
  const stats = allStats[id] || {
    times_reviewed: 0,
    best_score: null,
    last_reviewed: null,
  };
  return {
    times_reviewed: stats.times_reviewed,
    best_score: stats.best_score,
    last_reviewed: stats.last_reviewed,
    total_cards_revealed: 0,
  };
}

export function toggleExamplePin(id) {
  const pinned = JSON.parse(localStorage.getItem(PINNED_EXAMPLES_KEY) || "[]");
  const isPinned = pinned.includes(id);
  const updated = isPinned ? pinned.filter((p) => p !== id) : [...pinned, id];
  localStorage.setItem(PINNED_EXAMPLES_KEY, JSON.stringify(updated));
  return { pinned: !isPinned };
}

export function getPinnedExamples() {
  return JSON.parse(localStorage.getItem(PINNED_EXAMPLES_KEY) || "[]");
}

// Get all raw decks (used for migration prompt on login)
export function getAllGuestDecks() {
  return getDecks();
}

// Clear all guest data (called after migration or on login regardless)
export function clearGuestData() {
  localStorage.removeItem(DECKS_KEY);
  localStorage.removeItem(DISMISSED_EXAMPLES_KEY);
  localStorage.removeItem(EXAMPLE_STATS_KEY);
  localStorage.removeItem(EXAMPLE_FIRST_SEEN_KEY);
  localStorage.removeItem(PINNED_EXAMPLES_KEY);
}
